config/routes.rb
Rails.application.routes.draw do
  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home' ,to: 'home#index'
  get 'find-driver' ,to: 'home#find_ride'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'dijkstra'
  require 'drivers'
  include Dijkstra
  include Driver

  def index

  end

  def get_path(parents,dst,results)
    results.push(dst)
    if parents[dst] == -1
      return results
    else
      get_path(parents,parents[dst],results)
    end
  end
  # Euclidian Distance to find closest driver
  def find_distance(x1,x2,y1,y2)
    sum_of_squares = ((x1.to_f-x2.to_f)**2)+((y1.to_f-y2.to_f)**2)
    Math.sqrt( sum_of_squares )
  end
  def find_ride
    drivers = []
    driver_1 = Driver.new('Han Solo','015895656',1,0)
    driver_2 = Driver.new('Luke Skywalker','015895656',3,0)
    driver_3 = Driver.new('Darth Vader','015895656',0,4)
    drivers.push driver_1
    drivers.push driver_2
    drivers.push driver_3

    x_cod_user = params[:x_cod]
    y_cod_user = params[:y_cod]
    user_from = params[:from_location].to_i
    user_to = params[:to_location].to_i
    @closest_driver = nil
    @closest_distance = 999999999 #Infinite
    drivers.each do |driver|
      if @closest_driver.nil?
        @closest_driver = driver
        @closest_distance = find_distance(x_cod_user,driver.x,y_cod_user,driver.y)
      elsif find_distance(x_cod_user,driver.x,y_cod_user,driver.y)< @closest_distance
        @closest_distance = find_distance(x_cod_user,driver.x,y_cod_user,driver.y)
        @closest_driver = driver
      end
    end

    graph = Graph.new
    (1..6).each {|node| graph.push node }
    graph.connect_mutually 1, 2, 7
    graph.connect_mutually 1, 3, 9
    graph.connect_mutually 1, 6, 14
    graph.connect_mutually 2, 3, 10
    graph.connect_mutually 2, 4, 15
    graph.connect_mutually 3, 4, 11
    graph.connect_mutually 3, 6, 2
    graph.connect_mutually 4, 5, 6
    graph.connect_mutually 5, 6, 9

    # p graph
    # p graph.length_between(2, 1)
    # p graph.neighbors(1)
    paths =  graph.dijkstra(user_from, user_to)
    @result = get_path(paths,user_to,[])
    @result.reverse!
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/home/find_ride.html.erb
<%= @closest_driver.name %><br>
Phone: <%= @closest_driver.phone %><br>
Driver is <%= @closest_distance %>km away.<br>
Optimal Route -> <% @result.each do |area| %>
  <%= Location.find(area).name %>
<% end %>

app/views/home/index.html.erb
<form action="/find-driver" method="get">
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  <label>From</label>
  <select name="from_location">
    <% (1..6).each do |location|%>
      <option value="<%=location %>"><%=Location.find(location).name %></option>
    <% end %>
  </select><br>
  <label>To</label>
  <select name="to_location">
    <% (1..6).each do |location|%>
      <option value="<%=location %>"><%=Location.find(location).name %></option>
    <% end %>
  </select><br>
  <label>X Coordinate</label>
  <input type="number" name="x_cod">
  <label>Y Coordinate</label>
  <input type="number" name="y_cod">
  <input type="submit" value="Find">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ncred</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>